site_name: webTest测试框架
site_author: wuranxu
edit_uri: ""  
theme:
  name: "material"
  logo: assets/logo.svg
  favicon: assets/logo.svg
  custom_dir: overrides
  palette:
    primary: purple
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.top

repo_url: https://github.com/wuranxu/webTest

extra:
  disqus: 'webTest'
  # analytics:
  #   provider: custom 


plugins:
  - search:
      lang: ja

extra_css:
  - stylesheets/extra.css

extra_javascript:
    - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'


markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

nav:
  - 立即开始: index.md

  - 智囊团: friends/公众号.md

  - 联系作者: friends/联系作者.md


